dash/sample_code/python/chapter/chapter_18/making_pages/ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.api.v2.views import PagesAPIViewSet
from wagtail.contrib.sitemaps import Sitemap
from wagtail.documents import urls as wagtaildocs_urls

from apps.web.sitemaps import StaticViewSitemap

PagesAPIViewSet.schema = None  # hacky workaround for https://github.com/wagtail/wagtail/issues/8583

sitemaps = {
    "static": StaticViewSitemap(),
    "wagtail": Sitemap(),
}

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("apps.dashboard.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("accounts/", include("allauth_2fa.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("ecommerce/", include("apps.ecommerce.urls")),
    path("", include("apps.web.urls")),
    path("pegasus/", include("pegasus.apps.examples.urls")),
    path("pegasus/employees/", include("pegasus.apps.employees.urls")),
    path("tutorial/", include("tutorial.apps.basics.urls")),
    path("group-chat/", include("apps.group_chat.urls")),
    path("chat/", include("apps.chat.urls")),
    path("openai/", include("apps.openai_example.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # wagtail config
    # redirect Wagtail admin login to main login page
    path("cms/login/", RedirectView.as_view(pattern_name="account_login")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("content/", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

pegasus/apps/employees/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views

app_name = "pegasus_employees"

urlpatterns = [
    path(
        "objects/",
        login_required(
            TemplateView.as_view(
                template_name="pegasus/employees/object_lifecycle_home.html",
                extra_context={"active_tab": "object_lifecycle"},
            )
        ),
        name="object_lifecycle_home",
    ),
    path("objects/react/", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle"),
    path("objects/react/<path:path>", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle_w_path"),
    path("charts/", views.ChartsView.as_view(), name="charts"),
    path("api/employee-data/", views.EmployeeDataAPIView.as_view(), name="employee_data"),
]


# drf config
router = routers.DefaultRouter()
router.register("api/employees", views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "pegasus_examples"

urlpatterns = [
    path("", views.ExamplesHomeView.as_view(), name="examples_home"),
    path(
        "landing-page/",
        TemplateView.as_view(
            template_name="pegasus/examples/example_landing_page.html", extra_context={"active_tab": "landing_page"}
        ),
        name="landing_page",
    ),
    path(
        "pricing-page/",
        TemplateView.as_view(
            template_name="pegasus/examples/example_pricing_page.html", extra_context={"active_tab": "pricing_page"}
        ),
        name="pricing_page",
    ),
    # these are experimental examples that aren't currently exposed in the UI.
    path("alpine/", TemplateView.as_view(template_name="pegasus/examples/alpine_demo.html"), name="alpine_demo"),
    path("forms/", views.ExampleFormView.as_view(), name="form_demo"),
    path("forms/alpine/", views.AlpineFormView.as_view(), name="alpine_form_demo"),
    # tasks
    path("tasks/", views.TasksView.as_view(), name="tasks"),
    path("tasks/api/", views.tasks_api, name="tasks_api"),
]

pegasus/apps/employees/models.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ("hr", "Human Resources"),
        ("finance", "Finance"),
        ("engineering", "Engineering"),
        ("marketing", "Marketing"),
        ("sales", "Sales"),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="employees")
    name = models.CharField(max_length=100, help_text="Your employee's name.")
    department = models.CharField(
        max_length=20, choices=DEPARTMENT_CHOICES, help_text="What department your employee belongs to."
    )
    salary = models.PositiveIntegerField(help_text="Your employee's annual salary.")

    def __str__(self):
        return self.name

pegasus/apps/employees/forms.py
from django import forms

from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("name", "department", "salary")

pegasus/apps/examples/forms.py
from django import forms
from django.forms import DateInput
from django.utils.translation import gettext


class ExampleForm(forms.Form):
    COLORS = (
        ("red", "Red"),
        ("blue", "Blue"),
        ("green", "Green"),
        ("yellow", "Yellow"),
    )
    name = forms.CharField(help_text="This is a character field. It is required.")
    email = forms.EmailField(help_text="This is an email field. It is required.")
    date = forms.DateField(help_text="This is a date field. It is required.", widget=DateInput(attrs={"type": "date"}))

    invisible = forms.CharField(
        help_text="This is an Invisible field.", widget=forms.HiddenInput(), initial="something"
    )
    website = forms.URLField(help_text="This is a URL field. It is required.")
    checkbox = forms.BooleanField(help_text="This is a checkbox / boolean field", required=False)
    favorite_color = forms.ChoiceField(help_text="This is a choice field", choices=COLORS)
    comments = forms.CharField(
        help_text="This is a longer character field. It is optional", required=False, widget=forms.Textarea()
    )
    centered_input = forms.CharField(
        help_text="This is an optional input centered text.",
        required=False,
        widget=forms.TextInput(
            attrs={"class": "pg-text-centered"},
        ),
    )
    centered_text = forms.CharField(
        help_text="This is an optional text area with centered text.",
        required=False,
        widget=forms.Textarea(
            attrs={"class": "pg-text-centered"},
        ),
    )


class ExampleFormAlpine(forms.Form):
    YES_NO_OTHER = (
        ("yes", gettext("Yes")),
        ("no", gettext("No")),
        ("other", gettext("Other")),
    )
    STYLES = (
        ("regular", gettext("Normal")),
        ("success", gettext("Success")),
        ("danger", gettext("Danger")),
    )
    like_django = forms.ChoiceField(
        label=gettext("Do you like Django?"),
        help_text=gettext("Try choosing 'other' to see unhiding a form field based on a value."),
        choices=YES_NO_OTHER,
        widget=forms.Select(attrs={"x-model": "likeDjango"}),
    )
    like_django_other = forms.CharField(label=gettext("Please specify more details about your answer."))
    styled_options = forms.ChoiceField(
        label=gettext("Styled Options"),
        help_text=gettext("Try picking an option to see how you can style a component based on its value."),
        choices=STYLES,
        widget=forms.Select(attrs={"x-model": "styleValue"}),
    )

pegasus/apps/employees/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Count, Sum
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.templatetags.static import static
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods, require_POST
from django.views.generic import TemplateView
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from .forms import EmployeeForm
from .models import Employee
from .serializers import AggregateEmployeeDataSerializer, EmployeeSerializer


@login_required
def employee_list(request):
    return render(
        request,
        "pegasus/employees/list_employees.html",
        {"active_tab": "object_lifecycle", "employees": Employee.objects.filter(user=request.user)},
    )


@login_required
def new_employee(request):
    return _add_edit_employee(request)


@login_required
def edit_employee(request, employee_id):
    # don't forget to filter by user, else you'll allow people to edit other people's employees!
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee(request, employee)


def _add_edit_employee(request, employee: Employee = None):
    if employee:
        assert employee.user == request.user
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))
    else:
        form = EmployeeForm(instance=employee)

    return render(
        request,
        "pegasus/employees/edit_employee.html",
        {
            "active_tab": "object_lifecycle",
            "employee": employee,
            "form": form,
        },
    )


@require_POST
@login_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))




@method_decorator(login_required, name="dispatch")
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            "department_choices": [{"id": c[0], "name": c[1]} for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = "pegasus/employees/react_object_lifecycle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "framework_url": "https://reactjs.org/",
                "framework_name": "React",
                "framework_icon": static("images/pegasus/react-icon.png"),
                "active_tab": "object_lifecycle",
                "url_base": reverse("pegasus_employees:react_object_lifecycle"),
            }
        )
        return context


@method_decorator(login_required, name="dispatch")
class ChartsView(TemplateView):
    template_name = "pegasus/employees/charts.html"

    def get_context_data(self, **kwargs):
        return {
            "active_tab": "charts",
        }


class EmployeeDataAPIView(APIView):
    @extend_schema(operation_id="employees_aggregate_data", responses={200: AggregateEmployeeDataSerializer})
    def get(self, request):
        user = request.user
        data = user.employees.values("department").annotate(
            average_salary=Avg("salary"),
            total_cost=Sum("salary"),
            number_employees=Count("pk"),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [[row["department"], row["total_cost"]] for row in data]
        average_salaries = [[row["department"], row["average_salary"]] for row in data]
        headcounts = [[row["department"], row["number_employees"]] for row in data]
        return Response(
            {
                "total_costs": total_costs,
                "average_salaries": average_salaries,
                "headcounts": headcounts,
            }
        )


@extend_schema_view(
    create=extend_schema(operation_id="employees_create"),
    list=extend_schema(operation_id="employees_list"),
    retrieve=extend_schema(operation_id="employees_retrieve"),
    update=extend_schema(operation_id="employees_update"),
    partial_update=extend_schema(operation_id="employees_partial_update"),
    destroy=extend_schema(operation_id="employees_destroy"),
)
class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

pegasus/apps/examples/views/form_views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import FormView

from pegasus.apps.examples.forms import ExampleForm, ExampleFormAlpine


class ExampleFormView(FormView):
    template_name = "pegasus/examples/example_form.html"
    form_class = ExampleForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        messages.success(self.request, "Thanks for filling in the form!")
        return redirect("pegasus_examples:examples_home")


class AlpineFormView(FormView):
    template_name = "pegasus/examples/example_form_alpine.html"
    form_class = ExampleFormAlpine

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        messages.success(self.request, "Thanks for filling in the form!")
        return redirect("pegasus_examples:examples_home")

pegasus/apps/examples/views/tasks_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name="dispatch")
class TasksView(TemplateView):
    template_name = "pegasus/examples/tasks.html"

    def get_context_data(self, **kwargs):
        return {
            "active_tab": "tasks",
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

templates/pegasus/examples/alpine_demo.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% block app %}
  <div class="app-card">
    <h1 class="pg-title">AlpineJS Demo</h1>
    <h2 x-data="{ message: 'I ❤️ Alpine' }" x-text="message" class="pg-subtitle"></h2>
    <div x-data="{ count: 0 }" class="mt-2">
      <button x-on:click="count++" class="pg-button-secondary">Increment</button>
      <span x-text="count"></span>
    </div>
    <div x-data="{ open: false }" class="mt-2">
      <button @click="open = ! open" class="pg-button-secondary">Toggle</button>
      <div x-show="open" @click.outside="open = false" class="mt-1">Contents...</div>
    </div>
    <div class="mt-2"
      x-data="{
          search: '',

          items: ['foo', 'bar', 'baz'],

          filteredItems() {
              return this.items.filter(
                  i => i.startsWith(this.search)
              )
          }
      }"
  >
      <input x-model="search" placeholder="Search..." class="pg-control">

      <ul class="mt-1">
          <template x-for="item in filteredItems()" :key="item">
              <li x-text="item"></li>
          </template>
      </ul>
    </div>
  </div>
{% endblock %}

templates/pegasus/examples/example_form.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load form_tags %}
{% block app %}
<section class="app-card">
  <h2 class="pg-subtitle">Example Form</h2>
  <form method="post">
    {% csrf_token %}
    {% render_form_fields form %}
    <input type="submit" value="Save Data" class="pg-button-secondary">
  </form>
</section>
{% endblock %}

templates/pegasus/examples/example_form_alpine.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load form_tags %}
{% block app %}
<section class="app-card">
  <h2 class="pg-subtitle">Example Form with Alpine.js customizations</h2>
  <form method="post" x-data="{ likeDjango: '{{ form.like_django.data|default:"yes" }}', styleValue: '{{ form.styled_options.data|default:"regular" }}' }">
    {% csrf_token %}
    {% render_field form.like_django %}
    {% render_field form.like_django_other xshow="likeDjango === 'other'" xcloak='True' %}
    {% render_field form.styled_options xbind__class="'pg-bg-' + styleValue" %}
    <p class="mt-4">You can also use alpine to display selected values.
      <em>
        Like Django: <strong x-text="likeDjango"></strong>,
        Style: <strong x-text="styleValue"></strong>
      </em>
    </p>
    <input type="submit" value="Save Data" class="pg-button-secondary mt-2">
  </form>
</section>
{% endblock %}

templates/pegasus/examples/example_landing_page.html
{% extends "web/base.html" %}
{% load static %}
{% block body %}

<div id="example-page-content">
<section class="section container">
    <div class="columns is-vcentered columns-reversed">
        <div class="column">
        </div>
        <div class="column">
            <h1 class="title is-size-2">My Amazing SaaS Application</h1>
            <h2 class="subtitle is-size-4">
                This app will be the greatest thing the world has ever seen.
            </h2>
            <p class="buttons">
                <a class="button is-primary is-large" href="#get-started">
                    Get Started
                </a>
                <a class="button is-primary is-large is-outlined" href="#pricing">
                    Pricing
                </a>
            </p>
        </div>
    </div>
</section>
<section class="section container is-size-5">
    <div class="columns">
        <div class="column is-one-quarter">
        </div>
        <div class="is-three-quarters">
            <div class="title">Powerful Built-In Features</div>
            <div class="subtitle">This is where you talk about the great features that your app has.</div>
            <div class="columns">
                <div class="column">
                    <span class="subfeature-title">Feature Number 1</span>
                    &mdash; A really great feature that everyone will love!
                </div>
                <div class="column">
                    <span class="subfeature-title">Feature Number 2</span>
                    &mdash; This feature is even better than Feature #1! A real crowd pleaser!
                </div>
                <div class="column">
                    <span class="subfeature-title">Feature 3</span>
                    &mdash; Possibly the best feature of all. This is some groundbreaking stuff that this app can do.
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section container is-size-5">
    <div class="columns columns-reversed">
        <div class="column is-one-quarter">
        </div>
        <div class="is-three-quarters">
            <div class="title">Another Section of Functionality</div>
            <div class="subtitle">Here you can add more things that you want to talk about.</div>
            <div class="columns">
                <div class="column">
                    <span class="subfeature-title">Extra Thing 1</span>
                    &mdash;This thing is important so it will be listed first.
                </div>
                <div class="column">
                    <span class="subfeature-title">Extra Thing 2</span>
                    &mdash;This thing is not as important as the first thing, so we've listed it second.
                </div>
                <div class="column">
                    <span class="subfeature-title">Extra Thing 2</span>
                    &mdash;This is the least important thing in this section.
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section container is-size-5">
    <div class="columns">
        <div class="column is-one-quarter">
        </div>
        <div class="is-three-quarters">
            <div class="title">A Third Section</div>
            <div class="subtitle">You are probably getting the picture now, but you can put as many of these sections as you want.</div>
            <div class="columns">
                <div class="column">
                    <span class="subfeature-title">Third Section Item 1</span>
                    &mdash;You don't have to have three items in each section. This one only has two.
                    The text here is a bit longer because we want to fill the space.
                </div>
                <div class="column">
                    <span class="subfeature-title">Third Section Item 2</span>
                    &mdash;This is the last one in this section. Phew, that was repetetive!
                    Now we can move onto a different layout / section of the page.
                </div>
            </div>
        </div>
    </div>
</section>
<section class="hero is-primary" >
    <div class="hero-body">
        <div class="container has-text-centered ">
            <h2 class="subtitle is-size-4 has-text-white">
                Just <del>$200</del> <strong>$99</strong> per month for new users! What a deal!
            </h2>
            <a class="button is-primary is-inverted is-medium" href="#get-started">
                Get Started
            </a>
        </div>
    </div>
</section>
<section class="section container is-size-5" id="faq">
    <div class="title">Frequently Asked Questions</div>
    <div class="columns question">
        <div class="column is-one-third has-text-weight-bold">
            What's this section all about?
        </div>
        <div class="column is-two-thirds">
            It's a simple two-column format that works great for a back and forth dialog
            like an FAQ.
        </div>
    </div>
    <div class="columns question">
        <div class="column is-one-third has-text-weight-bold">
            What does your app do?
        </div>
        <div class="column is-two-thirds content">
            <p>What <em>doesn't</em> the app do?</p>
            <p>It will solve all of your problems and a few problems you didn't even know you had!</p>
        </div>
    </div>
    <div class="columns question">
        <div class="column is-one-third has-text-weight-bold">
            What else can you tell me?
        </div>
        <div class="column is-two-thirds content">
            <p>
                Not too much. Each application is a unique snowflake and you'll have to come up with
                the right message for your application.
                This is just a layout to get you started!
            </p>
        </div>
    </div>
</section>
<section class="notification is-warning has-text-centered app-notice">
    <p>
        This is the example landing page that ships with Pegasus, which is heavily-based on Pegasus's own landing page.
    </p>
    <p>
        <a href="{% url 'pegasus_examples:examples_home' %}">Back to Dashboard</a>.
    </p>
</section>
</div>
{% endblock %}
{% block page_js %}
{% include 'pegasus/examples/components/sticky-header-js.html' %}
{% endblock %}

templates/pegasus/examples/examples_home.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% block app %}
<section class="app-card">
  <h1 class="pg-title">Examples Gallery</h1>
  <h2 class="pg-subtitle">
    End-to-end, fully functional examples for your project's needs.
  </h2>
</section>
  <div class="pg-columns">
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/object-demo-icons.png' %}" alt="Object Demo">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Employee Lifecycle</h3>
            <p>
              A front-end for working with your database implemented in vanilla Django, React, Vue.js, and HTMX.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_employees:object_lifecycle_home' %}" class="pg-button-secondary">
              <span>View Employee App</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/undraw/undraw_analytics.svg' %}" alt="Charts">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Charts</h3>
            <p>
              Fully-integrated charts based on real data from your application.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_employees:charts' %}" class="pg-button-secondary">
              <span>View Charts</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="pg-columns mt-2">
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/flags.png' %}" alt="Feature Flags">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Feature Flags</h3>
            <p>
              Use Feature Flags to enable or disable portions of your site dynamically.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_employees:charts' %}" class="pg-button-secondary">
              <span>View Feature Flag example</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/landing-page-screenshot-small.png' %}" alt="Landing Page">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Landing Page</h3>
            <p>
              A beautiful, responsive, and easy-to-customize landing page to help
              you tell your application's story.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:landing_page' %}" class="pg-button-secondary">
              <span>View Landing Page</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/celery-icon.png' %}" alt="Background Tasks">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Background Tasks</h3>
            <p>
              Support background, long-running, or scheduled tasks easily with a working Celery
              + front-end integration.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:tasks' %}" class="pg-button-secondary">
              <span>View Tasks</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
{% endblock %}